---
title: "Using OGC API Features services from R using geofi"
author: "Markus Kainu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using OGC API Features services from R using geofi}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE, 
  warning = FALSE,
  fig.height = 7,  
  fig.width = 7,
  dpi = 75
)
```


**Installation**

`geofi` can be installed from CRAN using

```{r, eval = FALSE}
# install from CRAN
install.packages("geofi")

# Install development version from GitHub
remotes::install_github("ropengov/geofi")
```

```{r}
# Let's first create a function that checks if the suggested 
# packages are available
check_namespaces <- function(pkgs){
  return(all(unlist(sapply(pkgs, requireNamespace,quietly = TRUE))))
}
```



```{r}
library(geofi)
library(sf)
library(ggplot2)

```

## Statistics Finland

```{r}
# create_bbox_area <- function(tessellation = "kunta", region_name = "helsinki"){
#   geofi::ogc_get_statfi_area(tessellation = tessellation)
# }

muni <- ogc_get_statfi_area(tessellation = "kunta", 
                          scale = 4500, 
                          output_crs = 4326,
                          # bbox = lappi_bbox,
                          limit=NULL)
dim(muni)
ggplot(muni) + geom_sf()

all <- ogc_get_statfi_area_pop(year = 2021,
                              # bbox = helsinki_bbox,
                              output_crs = 3067,
                              # limit = 22
                              )
dim(all)
ggplot(data = all) + geom_sf()
ggplot(data = all[grepl("^kunta", all$areaStatisticalUnit_inspireId_localId),]) + geom_sf()


ff <- ogc_get_statfi_area_pop(year = 2021,
                              output_crs = 4326
)
ggplot(data = ff[grepl("^kunta", ff$areaStatisticalUnit_inspireId_localId),], aes(fill = female_percentage)) + geom_sf()

helsinki <- geofi::get_municipalities() |>
  dplyr::filter(municipality_code == 91) |>
  sf::st_transform(4326)
helsinki_bbox <- paste0(sf::st_bbox(helsinki),collapse = ",")

lappi <- get_ogc_municipalities(tessellation = "maakunta", output_crs = 4326) |>
  dplyr::filter(geographicalName_fin == "Lappi")
lappi_bbox <- paste0(sf::st_bbox(lappi),collapse = ",")



grid5000 <- ogc_get_statfi_statistical_grid(resolution = 5000,
                                            bbox = helsinki_bbox#,
                                            # limit = 6
                                            )
mapview::mapview(grid5000)
#
grid1000 <- ogc_get_statfi_statistical_grid(resolution = 1000, bbox = helsinki_bbox)
#'
mapview::mapview(grid1000)
```


## National Land Survey

`options("geofi_mml_api_key" = Sys.getenv("MML_API_KEY"))`


```{r}
options("geofi_mml_api_key" = Sys.getenv("MML_API_KEY"))


res <- ogc_get_maastotietokanta_collections()
dplyr::as_tibble(res)

ff <- ogc_get_maastotietokanta(collection = "muuntoasema", bbox = helsinki_bbox)
dim(ff)
ggplot(ff) + geom_sf()
mapview::mapview(ff)


ogc_get_buildings_collections()

fff <- ogc_get_buildings(collection = "building_parts", limit = 100, bbox = "24.905568,60.190137,24.920717,60.194107")

mapview::mapview(fff)

fff <- ogc_get_nimisto(#search_string = "köyhäjoki"
  # limit = 100,
    bbox = "24.905568,60.190137,24.920717,60.194107"
                       )
mapview::mapview(fff)


```

