structure(list(url = "http://geo.stat.fi/geoserver/wfs?service=WFS&version=1.0.0&request=getFeature&typename=tilastointialueet%3Akunta4500k_2019", 
    status_code = 400L, headers = structure(list(date = "Fri, 05 Feb 2021 07:36:30 GMT", 
        server = "Apache-Coyote/1.1", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `content-disposition` = "inline; filename=geoserver-getFeature.text", 
        `content-encoding` = "gzip", `content-type` = "text/xml; subtype=gml/2.1.2", 
        `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 05 Feb 2021 07:36:30 GMT", 
            server = "Apache-Coyote/1.1", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `content-disposition` = "inline; filename=geoserver-getFeature.text", 
            `content-encoding` = "gzip", `content-type` = "text/xml; subtype=gml/2.1.2", 
            `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("CONTENT REMOVED FROM TEST"), 
    date = structure(1612510590, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.001044, 
    connect = 0.005984, pretransfer = 0.006044, starttransfer = 0.030615, 
    total = 0.05994)), class = "response")
