structure(list(url = "http://geo.stat.fi/geoserver/wfs?service=WFS&version=1.0.0&typeName=postialue:pno_2017&request=DescribeFeatureType", 
    status_code = 200L, headers = structure(list(date = "Sun, 18 Aug 2019 16:44:01 GMT", 
        server = "Apache-Coyote/1.1", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `content-disposition` = "inline; filename=geoserver-DescribeFeatureType.text", 
        `content-encoding` = "gzip", `content-type` = "text/xml", 
        `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 18 Aug 2019 16:44:01 GMT", 
            server = "Apache-Coyote/1.1", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `content-disposition` = "inline; filename=geoserver-DescribeFeatureType.text", 
            `content-encoding` = "gzip", `content-type` = "text/xml", 
            `access-control-allow-origin` = "*", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?><xsd:schema xmlns:gml=\"http://www.opengis.net/gml\" xmlns:postialue=\"http://www.postialueet.fi\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\" targetNamespace=\"http://www.postialueet.fi\">\n  <xsd:import namespace=\"http://www.opengis.net/gml\" schemaLocation=\"http://geoserv.stat.fi:8080/geoserver/schemas/gml/2.1.2/feature.xsd\"/>\n  <xsd:complexType name=\"pno_2017Type\">\n    <xsd:complexContent>\n      <xsd:extension base=\"gml:AbstractFeatureType\">\n        <xsd:sequence>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"objectid\" nillable=\"true\" type=\"xsd:decimal\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"posti_alue\" nillable=\"true\" type=\"xsd:string\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"nimi\" nillable=\"true\" type=\"xsd:string\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"namn\" nillable=\"true\" type=\"xsd:string\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"kunta\" nillable=\"true\" type=\"xsd:string\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"kuntanro\" nillable=\"true\" type=\"xsd:decimal\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"vuosi\" nillable=\"true\" type=\"xsd:decimal\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"pinta_ala\" nillable=\"true\" type=\"xsd:decimal\"/>\n          <xsd:element maxOccurs=\"1\" minOccurs=\"0\" name=\"geom\" nillable=\"true\" type=\"gml:MultiPolygonPropertyType\"/>\n        </xsd:sequence>\n      </xsd:extension>\n    </xsd:complexContent>\n  </xsd:complexType>\n  <xsd:element name=\"pno_2017\" substitutionGroup=\"gml:_Feature\" type=\"postialue:pno_2017Type\"/>\n</xsd:schema>\n"), 
    date = structure(1566146641, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000247, 
    connect = 0.01277, pretransfer = 0.012831, starttransfer = 0.051534, 
    total = 0.051717)), class = "response")
